PROGRESS = {'/lesson/home' => 1,
            '/' => 1,
            '/lesson/outback'=> 3,
            '/lesson/stare' => 4,
            '/lesson/enter' => 5,
            '/lesson/classic' => 5,
            '/finder/select?hdf_field=n' => 6,
            '/finder/select?hdf_field=s' => 6,
            '/finder/select' => 6,
            '/finder/got_counts' => 7,
            '/finder/irregulars' => 8,
            '/finder/next' => 9, 
            '/bias/index' => 11,
            '/bias/compare' => 12,
            '/sample/index' => 14,
            '/sample/go' => 15,
            '/funnel/magnify' => 16,
            '/funnel/smallest' => 17,
            '/funnel/best_region' => 18,
            '/funnel/you_got_it' => 19,
            '/funnel/compare_astronomer' => 20,
            '/funnel/you_versus' => 21,
            '/symmetry/enter' => 23,
            '/symmetry/sample' => 24,
            '/symmetry/evaluate' => 25,
            '/symmetry/question' => 26,
            '/symmetry/answer' => 27,
            '/symmetry/uniform' => 28,
            '/last/question' => 30,
            '/last/different' => 31,
            '/last/congratulations' => 32
        }
ASTRONOMER = {
      'n'=> [4.6, 24.7, 70.7],
      's'=> [5.1, 27.2, 67.2]
}